# Rune SDK configuration example

##################
# Authentication #
##################

# User Access Token
access_token_id: TODO
access_token_secret: TODO

# OR

# Client Key Pair
client_key_id: TODO
client_access_key: TODO
