# Rune SDK configuration example

##################
# Authentication #
##################

## Authentication method
# This key is only required if multiple kinds of authentication
# credentials are present in config
# One of 'access_token' or 'client_keys' or 'jwt'
auth_method: access_token

# User Access Token
access_token_id: TODO
access_token_secret: TODO

# OR

# Client Key Pair
# client_key_id: TODO
# client_access_key: TODO
